[fix] back top & Update README.md
FreeCodeCamp-Chengdu/Web-Conf pull request #51
Opened 2024-06-19 07:59 UTC by dethan3

1. Update README content,
2. add a `<div>` element return the page to the top.

close #49

2024-06-19 18:15 UTC, TechQuery requested changes
上游修复 EasyWebApp/cell-router#11 已发版：https://github.com/EasyWebApp/cell-router/releases/tag/v3.0.0-rc.8 ，请升级后提交新代码。

2024-06-20 01:02 UTC, dethan3 commented on README.md
> +<https://web-conf.dev/>
在 Markdown 中，`<https://web-conf.dev/>` 的格式称为“自动链接” (autolink)。这是将 URL 包含在尖括号 (`<>`) 中的一种简便方法，Markdown 解析器会自动将其转换为可点击的超链接。

例如：

```markdown
<https://web-conf.dev/>
```

显示效果如下：

<https://web-conf.dev/>

这种格式适用于 URL 和电子邮件地址。对于电子邮件地址，格式如下：

```markdown
<example@example.com>
```

显示效果如下：

<example@example.com>

以上回答来自于 chatGPT

详情可见：<https://www.markdownguide.org/basic-syntax/#urls-and-email-addresses>

2024-06-20 02:34 UTC, TechQuery commented on README.md
> +<https://web-conf.dev/>
现在几乎都用 [GFM 语法][1]，不用加括号。

[1]: https://github.github.com/gfm/#extended-url-autolink

2024-06-20 03:05 UTC, dethan3 commented on README.md
> +<https://web-conf.dev/>
我改回来了

2024-06-20 03:06 UTC, TechQuery approved these changes

2024-06-20 03:07 UTC, merged