网站界面国际化
FreeCodeCamp-Chengdu/Web-Conf pull request #53
Opened 2024-08-07 14:00 UTC by douxiaobo

- closes #52

2024-08-07 17:36 UTC, TechQuery requested changes
再复制、粘贴、翻译一份繁体中文 `zh-TW` 的。

2024-08-07 17:36 UTC, TechQuery commented on .gitpod.yml
除非你知道这是在干什么，否则不要提交与本任务无关的文件。

2024-08-07 17:36 UTC, TechQuery commented on source/component/TopNavBar.tsx
> +import { i18n } from '../i18n';
放到上面最后一个 `import` 语句下面。

2024-08-07 17:36 UTC, TechQuery commented on source/component/TopNavBar.tsx
>  export const TopNavBar: FC<TopNavBarProps> = ({ menu, ...rest }) => (
```suggestion
import { oberver } from 'web-cell';

export const TopNavBar: FC<TopNavBarProps> = observer(({ menu, ...rest }) => (
```
所有涉及 i18n 的组件都要变为观察者，才能相应语言切换去更新界面。

2024-08-07 17:36 UTC, TechQuery commented on source/index.webmanifest
> +    "lang": "en-US",
此处无需更改

2024-08-07 17:36 UTC, TechQuery commented on source/page/data.ts
>  ];
静态数据无法响应语言变更，需改为函数声明：
```diff
-export const common_menu = [
+export const common_menu = () => [
    { title: t('organizer_introduction'), href: 'community' },
    { title: t('national_it_events'), href: 'activity' }
];
```
外面使用处应该为函数调用：
```diff
-common_menu
+common_menu()
```
（下同）

2024-08-07 17:36 UTC, TechQuery commented on source/page/index.tsx
>                          </a>
```suggestion
                            freeCodeCamp {t('community_name')}
                        </a> &nbsp;
```
空格尽量放在标签外

2024-08-07 17:36 UTC, TechQuery commented on tsconfig.json
> +        "experimentalDecorators": false
无需变更，这个选项是默认值，我只是提醒老用户要注意关掉。

2024-08-07 17:36 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    aboutus: '关于我们',
```suggestion
    about_us: '关于我们',
```
单词要隔开，否则一眼看不懂是啥。

2024-08-07 17:36 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    homePagetitle: '成都 Web 开发者大会',
```suggestion
    chengdu_web_developer_summit: '成都 Web 开发者大会',
```
左边键名要和右边文本内容对应，除非文本过长时简述。

2024-08-08 05:32 UTC, douxiaobo commented on .gitpod.yml
好的。明白了，这个是自动生成的，我没有写。以后我要注意一下，我写过的内容都要提交。我从来没写过的文件，都不要提交。

2024-08-08 06:23 UTC, douxiaobo commented on source/component/TopNavBar.tsx
>  export const TopNavBar: FC<TopNavBarProps> = ({ menu, ...rest }) => (
我试了，import { observer } from 'web-cell';这个语句以后，显示上是灰暗的，看起来用不上。

2024-08-08 06:26 UTC, douxiaobo commented on source/page/data.ts
>  ];
![image](https://github.com/user-attachments/assets/4dc1c3d9-4a10-471b-a454-bd6b4f8f4aa0)
我试了，还是不行。我对TypeScript函数声明，不了解，我还没有学习TypeScript。

2024-08-08 06:46 UTC, douxiaobo commented on source/page/data.ts
>  ];
![image](https://github.com/user-attachments/assets/3a9172bd-b1af-4cd7-b6e8-6ac8f9f5b690)

2024-08-08 09:57 UTC, TechQuery requested changes

2024-08-08 09:57 UTC, TechQuery commented on source/i18n/index.ts
> +    'zh-TW': () => import('./zh-TW')
```suggestion
    'zh-TW': () => import('./zh-TW'),
    'zh-HK': () => import('./zh-TW'),
    'en-US': () => import('./en-US')
```
中文都紧挨起来，下同。

2024-08-08 09:57 UTC, TechQuery commented on source/page/data.ts
> +common_menu();
```suggestion
```
声明的时候为什么要调用？

2024-08-08 09:57 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    contactus: '联系我们',
下划线

2024-08-08 09:57 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    homePagedescription: '中国西南地区 Web、JavaScript 全栈开发者的年度盛会',
小写、下划线

2024-08-08 09:57 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    wechat: '微信公众号',
```suggestion
    wechat_public_account: '微信公众号',
```

2024-08-08 09:57 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +        '{years} 年连办 {summits} 场技术干货大会，合办活动、中小分享会、动手训练营、线上直播不计其数'
仔细看上游库文档，这种写法不对。

2024-08-09 07:30 UTC, douxiaobo commented on source/page/data.ts
> +common_menu();
我是按照上面的内容，看到了函数调用，所以我写了。这次我就删除。

2024-08-09 08:11 UTC, douxiaobo commented on source/i18n/zh-CN.ts
> +        '{years} 年连办 {summits} 场技术干货大会，合办活动、中小分享会、动手训练营、线上直播不计其数'
我已经写好了，我不确定对不对。

2024-08-09 13:08 UTC, TechQuery requested changes

2024-08-09 13:08 UTC, TechQuery commented on source/i18n/en-US.ts
> +    }: Record<'a' | 'b' | 'c', string>) =>
函数的参数命名必须是语义化的单词，不要偷懒。

2024-08-09 13:08 UTC, TechQuery commented on source/i18n/index.ts
> +    'zh-HK': '繁體中文',
```suggestion
    'zh-TW': '正體中文',
    'zh-HK': '繁體中文',
```
语言命名尊重当地习惯。

2024-08-09 13:08 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    }: Record<'a' | 'b' | 'c', string>) => textJoin(a, ' 年连办 ', b, c),
```suggestion
    }: Record<'a' | 'b' | 'c', string>) => textJoin(a, '年连办', b, c),
```
不需要自己空格，这个工具函数就是为了适配不同语言的空格规则。

2024-08-09 13:08 UTC, TechQuery commented on source/i18n/zh-TW.ts
> +        ' 場技術幹貨大會，合辦活動、中小分享會、動手訓練營、線上直播不計其數'
```suggestion
    tech_conferences:
        '場技術幹貨大會，合辦活動、中小分享會、動手訓練營、線上直播不計其數'
```
文本的首尾空格在外面用 `textJoin()` 实现。

2024-08-09 13:08 UTC, TechQuery commented on source/page/data.ts
> +            c: textJoin(t('tech_conferences'))
多段文字才需要 join。

2024-08-09 13:08 UTC, TechQuery commented on source/page/data.ts
> +const { t, currentLanguage } = i18n;
当前语言的切换要放在组件那边实现（比如导航栏组件），而不是在数据这边。

2024-08-10 11:40 UTC, TechQuery requested changes

2024-08-10 11:40 UTC, TechQuery commented on source/page/data.ts
> +            number_of_times: summits.length,
```suggestion
            number_of_times: summits().length + '',
```
1. 函数不调用，怎么返回具体数据呢？
2. 里面定义了参数都是 `string` 类型，你却传了一个 `number`。

2024-08-10 12:04 UTC, douxiaobo commented on source/page/data.ts
> +            number_of_times: summits.length,
第一个问题，我回答不出来，是我对TypeScript的函数调用不够深刻理解。第二个问题，之前我一直不知道，现在我才知道了summits().length是number。我按照上面的代码，结果还是出现同样的对话框。我试了tostring和number，还是不行，结果一样出现同样的对话框。

2024-08-10 12:30 UTC, TechQuery commented on source/page/data.ts
> +            number_of_times: summits.length,
> 第一个问题，我回答不出来，是我对TypeScript的函数调用不够深刻理解。

调用是一个运行时的概念，一切运行时概念都是 JavaScript 的，因为浏览器只能运行 JavaScript，而 TypeScript 只是开发和编译时的类型系统。

因此你要尽快多刷 fCC 基础题。

> 第二个问题，之前我一直不知道，现在我才知道了summits().length是number。我按照上面的代码，结果还是出现同样的对话框。我试了tostring和number，还是不行，结果一样出现同样的对话框。

你鼠标指到每一个传给参数的值，你会发现不止一个不是 `string`。

2024-08-10 13:16 UTC, douxiaobo commented on source/page/data.ts
> +            number_of_times: summits.length,
好的，现在看见了。从明天开始，刷Leetcode的时间缩短，花多一些时间放在fCC基础题。

2024-08-12 08:34 UTC, TechQuery requested changes

2024-08-12 08:34 UTC, TechQuery commented on source/page/data.ts
> +            which_year: years,
```suggestion
            which_year: years + '',
```

2024-08-12 12:18 UTC, TechQuery requested changes

2024-08-12 12:18 UTC, TechQuery commented on source/i18n/en-US.ts
> +
```suggestion
            number_of_times,
            long_sentence
        ),
```
此处无需变更，类型都是写对的，只要注意外面使用的时候按照类型来传值就行了。

2024-08-12 12:18 UTC, TechQuery commented on source/index.tsx
>      self.alert(message);
此处直接改为
```JS
    if (message) window.alert(message);
```

2024-08-12 12:18 UTC, TechQuery commented on source/page/data.ts
> +            which_year: years.toString + ' ',
`toString` 是一个方法（在对象上的一个函数），你要调用它而不是引用它：

```suggestion
            which_year: years.toString() + '',
```

2024-08-12 13:47 UTC, TechQuery requested changes

2024-08-12 13:47 UTC, TechQuery commented on source/index.tsx
>      if (!message) return;
```suggestion
```

2024-08-12 13:47 UTC, TechQuery commented on source/index.tsx
> +    // self.alert(message);
```suggestion
```
读明白变更是为什么，老代码就删掉，不要留一大堆注释。

实在什么问题，Git 里有所有历史记录，可以翻出来。

2024-08-15 11:43 UTC, TechQuery requested changes

2024-08-15 11:43 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +        'freeCodeCamp 成都社区一直以为成都技术爱好者以及用户提供一个开放的交流环境为目的，在过去的一年里，我们成功举办了30余次的社区活动，受到大家的一致好评和热烈响应。2017年已接近尾声，在组织部何青松的倡议下，我们特筹办freeCodeCamp【2017成都WEB前端交流大会】，为成都前端圈的技术工程师、爱好者提供一场前所未有的饕餮盛宴。在此，我们向您发出诚挚的邀请，
```suggestion
        'freeCodeCamp 成都社区一直以为成都技术爱好者以及用户提供一个开放的交流环境为目的，在过去的一年里，我们成功举办了 30 余次的社区活动，受到大家的一致好评和热烈响应。2017 年已接近尾声，在组织部何青松的倡议下，我们特筹办 freeCodeCamp【2017 成都 Web 前端交流大会】，为成都前端圈的技术工程师、爱好者提供一场前所未有的饕餮盛宴。在此，我们向您发出诚挚的邀请，此次盛会期待您的参与！',
```
1. 中英文、数字间要留有空格
2. 非缩写单词要注意大小写

2024-08-15 11:43 UTC, TechQuery commented on source/i18n/zh-HK.ts
> +import { textJoin } from 'mobx-i18n';
如果你是直接从台湾正体中文那边复制、粘贴，而没有针对港澳地区的专门用词，那就可以直接复用台湾版，无需新建文件。

2024-08-15 11:43 UTC, TechQuery commented on source/page/2017/index.tsx
>  export default () => (
```suggestion
export default observer(() => (
```

2024-08-15 11:43 UTC, TechQuery commented on source/i18n/zh-CN.ts
> +    activity_introduction: '活动介绍',
每年大会的翻译可以放在当年文件夹下面，然后再 `import` 进来合并到当前对象。

2024-08-16 07:25 UTC, douxiaobo commented on source/page/2017/index.tsx
>  export default () => (
我试了，网页上是空白的。所以，我删除了observer()，网页上有内容了。

2024-08-16 12:35 UTC, TechQuery requested changes

2024-08-16 12:35 UTC, TechQuery commented on source/i18n/en-US.ts
>  export default {
```suggestion
import enUS_2017 from '../page/2017/translation/en-US';

export default {
  ...enUS_2017,
```
以此类推，这样就只需要初始化一个 `TranslationModel` 就可以了，还能复用不同页面上可能会相同的一些文本。

2024-08-16 12:35 UTC, TechQuery commented on source/page/2017/index.tsx
> +import { observer } from 'web-cell';
放到第 8 行，遵循“外部包在前、内部包在后”的原则。

2024-08-19 15:52 UTC, TechQuery requested changes

2024-08-19 15:52 UTC, TechQuery commented on source/i18n/en-US.ts
>  export default {
```suggestion
import { textJoin } from 'mobx-i18n';

import enUS_2017 from '../page/2017/i18n/en-US';

 export default {
```
导入内外部模块和导出之间都空一行会比较清晰。

2024-08-19 15:52 UTC, TechQuery commented on source/page/2017/data.ts
> +import { i18n } from './i18n';
```suggestion
import { i18n } from '../../i18n';
```
引用全局统一的翻译存储。

2024-08-19 15:52 UTC, TechQuery commented on source/page/2017/i18n/index.ts
> +import { TranslationModel } from 'mobx-i18n';
不需要初始化多个翻译存储对象，统一使用全局的，各子页面的同类文件删掉。

2024-08-21 13:58 UTC, TechQuery requested changes

2024-08-21 13:58 UTC, TechQuery commented on source/page/2018-Code4City/data.ts
> +        name: t('hu_shenquan'), //http://localhost:1234打不开了，就搁置了，打算明天再看看。
具体什么报错？请发在下面。

2024-08-21 13:58 UTC, TechQuery commented on source/page/2018-Code4City/index.tsx
> +                            {t('hackathon_competition_2018')} //显示不了英文。
因为这个组件没有包 `observer()`。

2024-08-23 17:23 UTC, TechQuery requested changes

2024-08-23 17:23 UTC, TechQuery commented on source/page/2019/PageAccount.tsx
> +const { t } = i18n;
```suggestion
import { i18n } from '../../i18n';
import { PageFrame } from './PageFrame';

const { t } = i18n;
```

2024-09-05 02:26 UTC, TechQuery approved these changes

2024-09-05 02:26 UTC, merged

2024-09-05 05:17 UTC, TechQuery commented on pnpm-lock.yaml
这个文件为什么删掉？你本地没有安装整个项目吗？导致最新代码构建失败：https://github.com/FreeCodeCamp-Chengdu/Web-Conf/actions/runs/10712785599/job/29703754781#step:4:20